package com.document.Documentweb.constrant;

public enum ErrorCommon {
    SUBJECT_NOT_FOUND,
    CLASS_ALREADY_EXISTS, CLASS_NOT_FOUND, COMMENT_NOT_FOUND, POST_NOT_FOUND, SUBJECT_EXISTED, POST_DOES_NOT_EXIST, CLASS_DOES_NOT_EXIST, SUBJECT_DOES_NOT_EXIST, USER_DOES_NOT_EXIST;
}
