spring:
  application:
  name: Documentweb

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: ${YOUR_URL_MYSQL}
    username: ${YOUR_USERNAME_MYSQL}
    password: ${YOUR_PASSWORD_MYSQL}


  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB

jwt:
  signerKey: ${YOUR_SIGNER_KEY}
  expiration: 60  # 1 hour in seconds
  refreshable-duration: 120

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    persistAuthorization: true
    tryItOutEnabled: true
    csrf.enabled: true
    operationsSorter: method
    tags-sorter: alpha

avatar:
  upload-dir: uploads/avatars

openai:
  gemini:
    apiKey: ${YOUR_API_KEY_GEMINI}
    model: gemini-1.5-flash-latest:generateContent
    url: https://generativelanguage.googleapis.com/v1beta/models/
